ALTER TABLE AweSchTsk ADD COLUMN db VARCHAR(200);
ALTER TABLE AweSchTsk ADD COLUMN site VARCHAR(200);
ALTER TABLE HisAweSchTsk ADD COLUMN db VARCHAR(200);
ALTER TABLE HisAweSchTsk ADD COLUMN site VARCHAR(200);


