
/* BEGIN_SQLSERVER

  CREATE TABLE AweSchCal
   (	Ide INT  not NULL,
	Des VARCHAR(250)  not NULL,
	Act INT DEFAULT 1  not NULL,
	Nom VARCHAR(100)  not NULL
   )

    END_SQLSERVER */

     go

/* BEGIN_SQLSERVER

  CREATE TABLE AweSchCalDat
   (	Ide INT  not NULL,
	IdeCal INT  not NULL,
	Nom VARCHAR(40) ,
	Dat DATETIME
   )

      END_SQLSERVER */

	go

/* BEGIN_SQLSERVER

  CREATE TABLE AweSchTskFilMod
   (	IdeTsk VARCHAR(256)  not NULL,
	FilPth VARCHAR(40) ,
	ModDat DATETIME
   )

      END_SQLSERVER */

	go

/* BEGIN_SQLSERVER


  CREATE TABLE AweSchExe
   (	IdeTsk INT not NULL,
	IniDat DATETIME not NULL,
	EndDat DATETIME,
	ExeTim INT,
	Sta INT not NULL
   )

      END_SQLSERVER */

	go

	/* BEGIN_SQLSERVER


  CREATE TABLE AweSchSrv
   (	Ide INT not NULL,
	Nom VARCHAR(40) not NULL,
	Pro VARCHAR(10) not NULL,
	Hst VARCHAR(40) not NULL,
	Prt VARCHAR(10) not NULL,
	Act INT DEFAULT 1 not NULL
   )

    END_SQLSERVER */

	go

		/* BEGIN_SQLSERVER

  CREATE TABLE AweSchTsk
   (	Ide INT  not NULL,
	Nam VARCHAR(40)  not NULL,
	Des VARCHAR(250),
	NumStoExe INT,
	TimOutExe INT,
	TypExe INT  not NULL,
	IdeSrvExe INT,
	CmdExe VARCHAR(250)  not NULL,
	TypLch INT  not NULL,
	LchDepErr INT DEFAULT 0  not NULL,
	LchDepWrn INT DEFAULT 0  not NULL,
	LchSetWrn INT DEFAULT 0  not NULL,
	RepTyp INT DEFAULT 0  not NULL,
	RepEmaSrv INT,
	RepSndSta VARCHAR(20),
	RepEmaDst VARCHAR(250),
	RepTit VARCHAR(100),
	RepMsg VARCHAR(250),
	Act INT DEFAULT 1  not NULL,
	RepUsrDst VARCHAR(250),
  RepMntId VARCHAR(200),
  CmdExePth VARCHAR(200)
   )

    END_SQLSERVER */

	go

/* BEGIN_SQLSERVER

  CREATE TABLE AweSchTskAvgTim
   (	Ide INT not NULL,
	IdeTsk INT not NULL,
	AvgTim FLOAT not NULL,
	ExeDatTim VARCHAR(100)
   )

	    END_SQLSERVER */

	go

	/* BEGIN_SQLSERVER

  CREATE TABLE AweSchTskDpn
   (	IdeTsk INT not NULL,
	IdePrn INT not NULL,
	IsBlk INT not NULL,
	DpnOrd INT
   )

   	    END_SQLSERVER */

	go

		/* BEGIN_SQLSERVER


  CREATE TABLE AweSchTskLch
   (	Ide INT  not NULL,
	IdeTsk INT,
	RptNum INT,
	RptTyp INT,
	IniDat DATETIME,
	EndDat DATETIME,
	IniTim VARCHAR(8),
	EndTim VARCHAR(8),
	IdeCal INT,
	IdSrv INT,
	Pth VARCHAR(250),
	Pat VARCHAR(250),
	ExeHrs VARCHAR(200),
	ExeMth VARCHAR(200),
	ExeDay VARCHAR(200),
	ExeDte DATETIME,
	ExeTim VARCHAR(8),
	WeekDays VARCHAR(200),
	ExeYrs VARCHAR(200),
	ExeMin VARCHAR(200),
	ExeSec VARCHAR(200),
  SrvUsr VARCHAR(200),
  SrvPwd VARCHAR(200)
   )

   	    END_SQLSERVER */

	go

	/* BEGIN_SQLSERVER

  CREATE TABLE AweSchTskPar
   (	Ide INT not NULL,
	IdeTsk INT,
	Nam VARCHAR(40) not NULL,
	Val VARCHAR(400),
	Src INT not NULL,
	Typ VARCHAR(100) not NULL
   )

   	    END_SQLSERVER */

	go

		/* BEGIN_SQLSERVER

  CREATE TABLE HISAweSchCal
   (	HISope VARCHAR(20) not NULL,
	HISdat DATETIME not NULL,
	HISact VARCHAR(1) not NULL,
	Ide INT,
	Nom VARCHAR(40),
	Des VARCHAR(250),
	Act INT
   )

   	    END_SQLSERVER */

	go

	/* BEGIN_SQLSERVER

  CREATE TABLE HISAweSchCalDat
   (	HISope VARCHAR(20) not NULL,
	HISdat DATETIME not NULL,
	HISact VARCHAR(1) not NULL,
	Ide INT,
	IdeCal INT,
	Nom VARCHAR(40),
	Dat DATETIME
   )

      END_SQLSERVER */

	go

	/* BEGIN_SQLSERVER

  CREATE TABLE HISAweSchSrv
   (	HISope VARCHAR(20) not NULL,
	HISdat DATETIME not NULL,
	HISact VARCHAR(1) not NULL,
	Ide INT,
	Nom VARCHAR(40),
	Pro VARCHAR(10),
	Hst VARCHAR(40),
	Prt VARCHAR(10),
	Act INT
   )

         END_SQLSERVER */

	go

		/* BEGIN_SQLSERVER

  CREATE TABLE HISAweSchTsk
   (	HISope VARCHAR(20) not NULL,
	HISdat DATETIME not NULL,
	HISact VARCHAR(1) not NULL,
	Ide INT,
	IdePAR INT,
	Nam VARCHAR(40),
	Des VARCHAR(250),
	NumStoExe INT,
	TimOutExe INT,
	TypExe INT,
	IdeSrvExe INT,
	CmdExe VARCHAR(250),
	TypLch INT,
	LchDepErr INT,
	LchDepWrn INT,
	LchSetWrn INT,
	BLKPAR INT,
	RepTyp INT,
	RepEmaSrv INT,
	RepSndSta VARCHAR(20),
	RepEmaDst VARCHAR(250),
	RepTit VARCHAR(100),
	RepMsg VARCHAR(250),
	Act INT,
	RepUsrDst VARCHAR(250),
  RepMntId VARCHAR(200),
  CmdExePth VARCHAR(200)
   )

      END_SQLSERVER */

	go

	/* BEGIN_SQLSERVER

  CREATE TABLE HISAweSchTskLch
   (	HISope VARCHAR(20) not NULL,
	HISdat DATETIME not NULL,
	HISact VARCHAR(1) not NULL,
	Ide INT,
	IdeTsk INT,
	RptNum INT,
	RptTyp INT,
	IniDat DATETIME,
	EndDat DATETIME,
	IniTim VARCHAR(8),
	EndTim VARCHAR(8),
	IdeCal INT,
	IdSrv INT,
	Pth VARCHAR(250),
	Pat VARCHAR(250),
	ExeMth VARCHAR(200),
	ExeDay VARCHAR(200),
	ExeHrs VARCHAR(200),
	ExeDte DATETIME,
	ExeTim VARCHAR(8),
	WeekDays VARCHAR(200),
	ExeYrs VARCHAR(200),
	ExeMin VARCHAR(200),
	ExeSec VARCHAR(200),
  SrvUsr VARCHAR(200),
  SrvPwd VARCHAR(200)
   )

         END_SQLSERVER */

	go

		/* BEGIN_SQLSERVER

  CREATE TABLE HISAweSchTskPar
   (	HISope VARCHAR(20) not NULL,
	HISdat DATETIME not NULL,
	HISact VARCHAR(1) not NULL,
	Ide INT,
	IdeTsk INT,
	Nam VARCHAR(40),
	Val VARCHAR(400),
	Src INT,
	Typ VARCHAR(100)
   )

     END_SQLSERVER */

	go

   /* BEGIN_SQLSERVER

   ALTER TABLE AweSchCal ADD CONSTRAINT Nom_UQ  UNIQUE (Nom)

    END_SQLSERVER */

	go

   /* BEGIN_SQLSERVER

  ALTER TABLE AweSchCal ADD CONSTRAINT PK_AweSchCal UNIQUE (Ide)

      END_SQLSERVER */

  go

   /* BEGIN_SQLSERVER

  ALTER TABLE AweSchCalDat ADD CONSTRAINT PK_AweSchCalDat UNIQUE (Ide)

        END_SQLSERVER */

  go

   /* BEGIN_SQLSERVER

  CREATE INDEX AweSchExeI1 ON AweSchExe (IdeTsk, IniDat)

          END_SQLSERVER */

  go

   /* BEGIN_SQLSERVER

  ALTER TABLE AweSchSrv ADD CONSTRAINT PK_AweSchSrv UNIQUE (Ide)

	 END_SQLSERVER */

  go

   /* BEGIN_SQLSERVER

  ALTER TABLE AweSchTsk ADD CONSTRAINT PK_AweSchTsk UNIQUE (Ide)

  	 END_SQLSERVER */

  go

   /* BEGIN_SQLSERVER

  ALTER TABLE AweSchTskAvgTim ADD CONSTRAINT SYS_C00167154 UNIQUE (Ide)

    	 END_SQLSERVER */

  go

   /* BEGIN_SQLSERVER

  ALTER TABLE AweSchTskDpn ADD CONSTRAINT SYS_C00164575 UNIQUE (IdeTsk, IdePrn)

      	 END_SQLSERVER */

  go

   /* BEGIN_SQLSERVER

  ALTER TABLE AweSchTskLch ADD CONSTRAINT PK_AweSchTskLch UNIQUE (Ide)

      END_SQLSERVER */

  go

   /* BEGIN_SQLSERVER

  ALTER TABLE AweSchTskPar ADD CONSTRAINT PK_AweSchTskPar UNIQUE (Ide)

      END_SQLSERVER */

  go

/* BEGIN_SQLSERVER

  CREATE INDEX HISAweSchCalI1 ON HISAweSchCal (HISope, HISdat, HISact)

   END_SQLSERVER */

  go

/* BEGIN_SQLSERVER

  CREATE INDEX HISAweSchCalDatI1 ON HISAweSchCalDat (HISope, HISdat, HISact)

   END_SQLSERVER */

  go

/* BEGIN_SQLSERVER

  CREATE INDEX HISAweSchSrvI1 ON HISAweSchSrv (HISope, HISdat, HISact)

   END_SQLSERVER */

  go

/* BEGIN_SQLSERVER

  CREATE INDEX HISAweSchTskI1 ON HISAweSchTsk (HISope, HISdat, HISact)

   END_SQLSERVER */

  go

  /* BEGIN_SQLSERVER

  CREATE INDEX HISAweSchTskLchI1 ON HISAweSchTskLch (HISope, HISdat, HISact)

   END_SQLSERVER */

  go

/* BEGIN_SQLSERVER

  CREATE INDEX HISAweSchTskParI1 ON HISAweSchTskPar (HISope, HISdat, HISact)

   END_SQLSERVER */

  go

/* BEGIN_SQLSERVER

  ALTER TABLE AweSchCal ADD CONSTRAINT PK_AweSchCal PRIMARY KEY (Ide)

   END_SQLSERVER */

  go

/* BEGIN_SQLSERVER

  ALTER TABLE AweSchCalDat ADD CONSTRAINT PK_AweSchCalDat PRIMARY KEY (Ide)

   END_SQLSERVER */

  go

/* BEGIN_SQLSERVER

  ALTER TABLE AweSchTskFilMod ADD CONSTRAINT PK_AweSchTskFilMod PRIMARY KEY (IdeTsk,FilPth)

   END_SQLSERVER */

  go

/* BEGIN_SQLSERVER
  ALTER TABLE AweSchSrv ADD CONSTRAINT PK_AweSchSrv PRIMARY KEY (Ide)

   END_SQLSERVER */

  go

/* BEGIN_SQLSERVER

  ALTER TABLE AweSchTsk ADD CONSTRAINT PK_AweSchTsk PRIMARY KEY (Ide)

   END_SQLSERVER */

  go

/* BEGIN_SQLSERVER

  ALTER TABLE AweSchTskAvgTim ADD PRIMARY KEY (Ide)

  END_SQLSERVER */

 go

/* BEGIN_SQLSERVER

  ALTER TABLE AweSchTskDpn ADD PRIMARY KEY (IdeTsk, IdePrn)

  END_SQLSERVER */

 go

 /* BEGIN_SQLSERVER

  ALTER TABLE AweSchTskLch ADD CONSTRAINT PK_AweSchTskLch PRIMARY KEY (Ide)

   END_SQLSERVER */

  go

 /* BEGIN_SQLSERVER

  ALTER TABLE AweSchTskPar ADD CONSTRAINT PK_AweSchTskPar PRIMARY KEY (Ide)

  END_SQLSERVER */

 go


  /* BEGIN_ORACLE

CREATE TABLE "AWESCHCAL"
   (	"IDE" NUMBER(*,0),
	"DES" VARCHAR2(250 BYTE),
	"ACT" NUMBER(*,0) DEFAULT 1,
	"NOM" VARCHAR2(100 BYTE)
   );

END_ORACLE */

/* BEGIN_ORACLE

CREATE TABLE "AWESCHTSKFILMOD"
   (	"IDETSK" NUMBER(*,0),
	"FILPTH" VARCHAR2(256 BYTE),
	"MODDAT" DATE
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "AWESCHCALDAT"
   (	"IDE" NUMBER(*,0),
	"IDECAL" NUMBER(*,0),
	"NOM" VARCHAR2(40 BYTE),
	"DAT" DATE
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "AWESCHEXE"
   (	"IDETSK" NUMBER(*,0),
	"INIDAT" DATE,
	"ENDDAT" DATE,
	"EXETIM" NUMBER(*,0),
	"STA" NUMBER(*,0)
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "AWESCHSRV"
   (	"IDE" NUMBER(*,0),
	"NOM" VARCHAR2(40 BYTE),
	"PRO" VARCHAR2(10 BYTE),
	"HST" VARCHAR2(40 BYTE),
	"PRT" VARCHAR2(10 BYTE),
	"ACT" NUMBER(*,0) DEFAULT 1
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "AWESCHTSK"
   (	"IDE" NUMBER(*,0),
	"NAM" VARCHAR2(40 BYTE),
	"DES" VARCHAR2(250 BYTE),
	"NUMSTOEXE" NUMBER(*,0),
	"TIMOUTEXE" NUMBER(*,0),
	"TYPEXE" NUMBER(*,0),
	"IDESRVEXE" NUMBER(*,0),
	"CMDEXE" VARCHAR2(250 BYTE),
	"TYPLCH" NUMBER(*,0),
	"LCHDEPERR" NUMBER(*,0) DEFAULT 0,
	"LCHDEPWRN" NUMBER(*,0) DEFAULT 0,
	"LCHSETWRN" NUMBER(*,0) DEFAULT 0,
	"REPTYP" NUMBER(*,0) DEFAULT 0,
	"REPEMASRV" NUMBER(*,0),
	"REPSNDSTA" VARCHAR2(20 BYTE),
	"REPEMADST" VARCHAR2(250 BYTE),
	"REPTIT" VARCHAR2(100 BYTE),
	"REPMSG" VARCHAR2(250 BYTE),
	"ACT" NUMBER(*,0) DEFAULT 1,
	"REPUSRDST" VARCHAR2(250 BYTE),
  "REPMNTID" VARCHAR2(200 BYTE),
  "CMDEXEPTH" VARCHAR2(200 BYTE)
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "AWESCHTSKAVGTIM"
   (	"IDE" NUMBER(*,0),
	"IDETSK" NUMBER(*,0),
	"AVGTIM" FLOAT(126),
	"EXEDATTIM" VARCHAR2(100 BYTE)
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "AWESCHTSKDPN"
   (	"IDETSK" NUMBER(*,0),
	"IDEPRN" NUMBER(*,0),
	"ISBLK" NUMBER(*,0),
	"DPNORD" NUMBER(*,0)
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "AWESCHTSKLCH"
   (	"IDE" NUMBER(*,0),
	"IDETSK" NUMBER(*,0),
	"RPTNUM" NUMBER(*,0),
	"RPTTYP" NUMBER(*,0),
	"INIDAT" DATE,
	"ENDDAT" DATE,
	"INITIM" VARCHAR2(8 BYTE),
	"ENDTIM" VARCHAR2(8 BYTE),
	"IDECAL" NUMBER(*,0),
	"IDSRV" NUMBER(*,0),
	"PTH" VARCHAR2(250 BYTE),
	"PAT" VARCHAR2(250 BYTE),
	"EXEHRS" VARCHAR2(200 BYTE),
	"EXEMTH" VARCHAR2(200 BYTE),
	"EXEDAY" VARCHAR2(200 BYTE),
	"EXEDTE" DATE,
	"EXETIM" VARCHAR2(8 BYTE),
	"WEEKDAYS" VARCHAR2(200 BYTE),
	"EXEYRS" VARCHAR2(200 BYTE),
	"EXEMIN" VARCHAR2(200 BYTE),
	"EXESEC" VARCHAR2(200 BYTE),
  "SRVUSR" VARCHAR2(200 BYTE),
  "SRVPWD" VARCHAR2(200 BYTE)
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "AWESCHTSKPAR"
   (	"IDE" NUMBER(*,0),
	"IDETSK" NUMBER(*,0),
	"NAM" VARCHAR2(40 BYTE),
	"VAL" VARCHAR2(400 BYTE),
	"SRC" NUMBER(*,0),
	"TYP" VARCHAR2(100 BYTE)
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "HISAWESCHCAL"
   (	"HISOPE" VARCHAR2(20 BYTE),
	"HISDAT" DATE,
	"HISACT" VARCHAR2(1 BYTE),
	"IDE" NUMBER(*,0),
	"NOM" VARCHAR2(40 BYTE),
	"DES" VARCHAR2(250 BYTE),
	"ACT" NUMBER(*,0)
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "HISAWESCHCALDAT"
   (	"HISOPE" VARCHAR2(20 BYTE),
	"HISDAT" DATE,
	"HISACT" VARCHAR2(1 BYTE),
	"IDE" NUMBER(*,0),
	"IDECAL" NUMBER(*,0),
	"NOM" VARCHAR2(40 BYTE),
	"DAT" DATE
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "HISAWESCHSRV"
   (	"HISOPE" VARCHAR2(20 BYTE),
	"HISDAT" DATE,
	"HISACT" VARCHAR2(1 BYTE),
	"IDE" NUMBER(*,0),
	"NOM" VARCHAR2(40 BYTE),
	"PRO" VARCHAR2(10 BYTE),
	"HST" VARCHAR2(40 BYTE),
	"PRT" VARCHAR2(10 BYTE),
	"ACT" NUMBER(*,0)
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "HISAWESCHTSK"
   (	"HISOPE" VARCHAR2(20 BYTE),
	"HISDAT" DATE,
	"HISACT" VARCHAR2(1 BYTE),
	"IDE" NUMBER(*,0),
	"IDEPAR" NUMBER(*,0),
	"NAM" VARCHAR2(40 BYTE),
	"DES" VARCHAR2(250 BYTE),
	"NUMSTOEXE" NUMBER(*,0),
	"TIMOUTEXE" NUMBER(*,0),
	"TYPEXE" NUMBER(*,0),
	"IDESRVEXE" NUMBER(*,0),
	"CMDEXE" VARCHAR2(250 BYTE),
	"TYPLCH" NUMBER(*,0),
	"LCHDEPERR" NUMBER(*,0),
	"LCHDEPWRN" NUMBER(*,0),
	"LCHSETWRN" NUMBER(*,0),
	"BLKPAR" NUMBER(*,0),
	"REPTYP" NUMBER(*,0),
	"REPEMASRV" NUMBER(*,0),
	"REPSNDSTA" VARCHAR2(20 BYTE),
	"REPEMADST" VARCHAR2(250 BYTE),
	"REPTIT" VARCHAR2(100 BYTE),
	"REPMSG" VARCHAR2(250 BYTE),
	"ACT" NUMBER(*,0),
	"REPUSRDST" VARCHAR2(250 BYTE),
  "REPMNTID" VARCHAR2(200 BYTE),
  "CMDEXEPTH" VARCHAR(200 BYTE)
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "HISAWESCHTSKLCH"
   (	"HISOPE" VARCHAR2(20 BYTE),
	"HISDAT" DATE,
	"HISACT" VARCHAR2(1 BYTE),
	"IDE" NUMBER(*,0),
	"IDETSK" NUMBER(*,0),
	"RPTNUM" NUMBER(*,0),
	"RPTTYP" NUMBER(*,0),
	"INIDAT" DATE,
	"ENDDAT" DATE,
	"INITIM" VARCHAR2(8 BYTE),
	"ENDTIM" VARCHAR2(8 BYTE),
	"IDECAL" NUMBER(*,0),
	"IDSRV" NUMBER(*,0),
	"PTH" VARCHAR2(250 BYTE),
	"PAT" VARCHAR2(250 BYTE),
	"EXEMTH" VARCHAR2(200 BYTE),
	"EXEDAY" VARCHAR2(200 BYTE),
	"EXEHRS" VARCHAR2(200 BYTE),
	"EXEDTE" DATE,
	"EXETIM" VARCHAR2(8 BYTE),
	"WEEKDAYS" VARCHAR2(200 BYTE),
	"EXEYRS" VARCHAR2(200 BYTE),
	"EXEMIN" VARCHAR2(200 BYTE),
	"EXESEC" VARCHAR2(200 BYTE),
  "SRVUSR" VARCHAR2(200 BYTE),
  "SRVPWD" VARCHAR2(200 BYTE)
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE TABLE "HISAWESCHTSKPAR"
   (	"HISOPE" VARCHAR2(20 BYTE),
	"HISDAT" DATE,
	"HISACT" VARCHAR2(1 BYTE),
	"IDE" NUMBER(*,0),
	"IDETSK" NUMBER(*,0),
	"NAM" VARCHAR2(40 BYTE),
	"VAL" VARCHAR2(400 BYTE),
	"SRC" NUMBER(*,0),
	"TYP" VARCHAR2(100 BYTE)
   );

END_ORACLE */


  /* BEGIN_ORACLE

CREATE UNIQUE INDEX "NOM_UQ" ON "AWESCHCAL" ("NOM");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE UNIQUE INDEX "PK_AWESCHCAL" ON "AWESCHCAL" ("IDE");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE UNIQUE INDEX "PK_AWESCHCALDAT" ON "AWESCHCALDAT" ("IDE");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE INDEX "AWESCHEXEI1" ON "AWESCHEXE" ("IDETSK", "INIDAT");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE UNIQUE INDEX "PK_AWESCHSRV" ON "AWESCHSRV" ("IDE");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE UNIQUE INDEX "PK_AWESCHTSK" ON "AWESCHTSK" ("IDE");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE UNIQUE INDEX "SYS_C00167154" ON "AWESCHTSKAVGTIM" ("IDE");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE UNIQUE INDEX "SYS_C00164575" ON "AWESCHTSKDPN" ("IDETSK", "IDEPRN");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE UNIQUE INDEX "PK_AWESCHTSKLCH" ON "AWESCHTSKLCH" ("IDE");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE UNIQUE INDEX "PK_AWESCHTSKPAR" ON "AWESCHTSKPAR" ("IDE");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE INDEX "HISAWESCHCALI1" ON "HISAWESCHCAL" ("HISOPE", "HISDAT", "HISACT");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE INDEX "HISAWESCHCALDATI1" ON "HISAWESCHCALDAT" ("HISOPE", "HISDAT", "HISACT");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE INDEX "HISAWESCHSRVI1" ON "HISAWESCHSRV" ("HISOPE", "HISDAT", "HISACT");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE INDEX "HISAWESCHTSKI1" ON "HISAWESCHTSK" ("HISOPE", "HISDAT", "HISACT");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE INDEX "HISAWESCHTSKLCHI1" ON "HISAWESCHTSKLCH" ("HISOPE", "HISDAT", "HISACT");

END_ORACLE */


  /* BEGIN_ORACLE

CREATE INDEX "HISAWESCHTSKPARI1" ON "HISAWESCHTSKPAR" ("HISOPE", "HISDAT", "HISACT");

END_ORACLE */


  /* BEGIN_ORACLE

ALTER TABLE "AWESCHCAL" ADD CONSTRAINT "NOM_UQ" UNIQUE ("NOM");

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHCAL" ADD CONSTRAINT "PK_AWESCHCAL" PRIMARY KEY ("IDE");

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHCAL" MODIFY ("IDE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHCAL" MODIFY ("DES" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHCAL" MODIFY ("ACT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHCAL" MODIFY ("NOM" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHCALDAT" ADD CONSTRAINT "PK_AWESCHCALDAT" PRIMARY KEY ("IDE");

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKFILMOD" ADD PRIMARY KEY ("IDETSK", "FILPTH")

END_ORACLE */

 /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKFILMOD" MODIFY ("IDETSK" NOT NULL ENABLE);

END_ORACLE */

 /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKFILMOD" MODIFY ("FILPTH" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHCALDAT" MODIFY ("IDE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHCALDAT" MODIFY ("IDECAL" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHCALDAT" MODIFY ("NOM" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHCALDAT" MODIFY ("DAT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHEXE" MODIFY ("IDETSK" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHEXE" MODIFY ("INIDAT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHEXE" MODIFY ("STA" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHSRV" ADD CONSTRAINT "PK_AWESCHSRV" PRIMARY KEY ("IDE");

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHSRV" MODIFY ("IDE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHSRV" MODIFY ("NOM" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHSRV" MODIFY ("PRO" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHSRV" MODIFY ("HST" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHSRV" MODIFY ("PRT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHSRV" MODIFY ("ACT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSK" ADD CONSTRAINT "PK_AWESCHTSK" PRIMARY KEY ("IDE");

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSK" MODIFY ("IDE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSK" MODIFY ("NAM" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSK" MODIFY ("TYPEXE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSK" MODIFY ("CMDEXE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSK" MODIFY ("TYPLCH" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSK" MODIFY ("LCHDEPERR" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSK" MODIFY ("LCHDEPWRN" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSK" MODIFY ("LCHSETWRN" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSK" MODIFY ("REPTYP" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSK" MODIFY ("ACT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKAVGTIM" MODIFY ("IDE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKAVGTIM" MODIFY ("IDETSK" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKAVGTIM" MODIFY ("AVGTIM" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKAVGTIM" ADD PRIMARY KEY ("IDE");

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKDPN" MODIFY ("IDETSK" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKDPN" MODIFY ("IDEPRN" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKDPN" MODIFY ("ISBLK" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKDPN" ADD PRIMARY KEY ("IDETSK", "IDEPRN");

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKLCH" ADD CONSTRAINT "PK_AWESCHTSKLCH" PRIMARY KEY ("IDE");

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKLCH" MODIFY ("IDE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKPAR" ADD CONSTRAINT "PK_AWESCHTSKPAR" PRIMARY KEY ("IDE");

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKPAR" MODIFY ("IDE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKPAR" MODIFY ("NAM" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKPAR" MODIFY ("SRC" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "AWESCHTSKPAR" MODIFY ("TYP" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHCAL" MODIFY ("HISOPE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHCAL" MODIFY ("HISDAT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHCAL" MODIFY ("HISACT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHCALDAT" MODIFY ("HISOPE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHCALDAT" MODIFY ("HISDAT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHCALDAT" MODIFY ("HISACT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHSRV" MODIFY ("HISOPE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHSRV" MODIFY ("HISDAT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHSRV" MODIFY ("HISACT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHTSK" MODIFY ("HISOPE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHTSK" MODIFY ("HISDAT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHTSK" MODIFY ("HISACT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHTSKLCH" MODIFY ("HISOPE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHTSKLCH" MODIFY ("HISDAT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHTSKLCH" MODIFY ("HISACT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHTSKPAR" MODIFY ("HISOPE" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHTSKPAR" MODIFY ("HISDAT" NOT NULL ENABLE);

END_ORACLE */

  /* BEGIN_ORACLE

ALTER TABLE "HISAWESCHTSKPAR" MODIFY ("HISACT" NOT NULL ENABLE);

END_ORACLE */



/* BEGIN_SYBASE */

  CREATE TABLE AweSchCal
   (	Ide INT  not NULL,
	Des VARCHAR(250)  not NULL,
	Act INT DEFAULT 1  not NULL,
	Nom VARCHAR(100)  not NULL
   )

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  CREATE TABLE AweSchCalDat
   (	Ide INT  not NULL,
	IdeCal INT  not NULL,
	Nom VARCHAR(40) ,
	Dat DATETIME
   )

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */


  CREATE TABLE AweSchExe
   (	IdeTsk INT not NULL,
	IniDat DATETIME not NULL,
	EndDat DATETIME,
	ExeTim INT,
	Sta INT not NULL
   )

     go

    /* END_SYBASE */

	/* BEGIN_SYBASE */


  CREATE TABLE AweSchSrv
   (	Ide INT not NULL,
	Nom VARCHAR(40) not NULL,
	Pro VARCHAR(10) not NULL,
	Hst VARCHAR(40) not NULL,
	Prt VARCHAR(10) not NULL,
	Act INT DEFAULT 1 not NULL
   )

     go

    /* END_SYBASE */

		/* BEGIN_SYBASE */

  CREATE TABLE AweSchTsk
   (	Ide INT  not NULL,
	Nam VARCHAR(40)  not NULL,
	Des VARCHAR(250),
	NumStoExe INT,
	TimOutExe INT,
	TypExe INT  not NULL,
	IdeSrvExe INT,
	CmdExe VARCHAR(250)  not NULL,
	TypLch INT  not NULL,
	LchDepErr INT DEFAULT 0  not NULL,
	LchDepWrn INT DEFAULT 0  not NULL,
	LchSetWrn INT DEFAULT 0  not NULL,
	RepTyp INT DEFAULT 0  not NULL,
	RepEmaSrv INT,
	RepSndSta VARCHAR(20),
	RepEmaDst VARCHAR(250),
	RepTit VARCHAR(100),
	RepMsg VARCHAR(250),
	Act INT DEFAULT 1  not NULL,
	RepUsrDst VARCHAR(250),
  RepMntId VARCHAR(200),
  CmdExePth VARCHAR(200)
   )

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  CREATE TABLE AweSchTskAvgTim
   (	Ide INT not NULL,
	IdeTsk INT not NULL,
	AvgTim FLOAT not NULL,
	ExeDatTim VARCHAR(100)
   )

     go

    /* END_SYBASE */

	/* BEGIN_SYBASE */

  CREATE TABLE AweSchTskDpn
   (	IdeTsk INT not NULL,
	IdePrn INT not NULL,
	IsBlk INT not NULL,
	DpnOrd INT
   )

     go

    /* END_SYBASE */

		/* BEGIN_SYBASE */


  CREATE TABLE AweSchTskLch
   (	Ide INT  not NULL,
	IdeTsk INT,
	RptNum INT,
	RptTyp INT,
	IniDat DATETIME,
	EndDat DATETIME,
	IniTim VARCHAR(8),
	EndTim VARCHAR(8),
	IdeCal INT,
	IdSrv INT,
	Pth VARCHAR(250),
	Pat VARCHAR(250),
	ExeHrs VARCHAR(200),
	ExeMth VARCHAR(200),
	ExeDay VARCHAR(200),
	ExeDte DATETIME,
	ExeTim VARCHAR(8),
	WeekDays VARCHAR(200),
	ExeYrs VARCHAR(200),
	ExeMin VARCHAR(200),
	ExeSec VARCHAR(200),
  SrvUsr VARCHAR(200),
  SrvPwd VARCHAR(200)
   )

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  CREATE TABLE AweSchTskFilMod
   (	IdeTsk INT not NULL,
	FilPth VARCHAR(256) not NULL,
	ModDat DATETIME
   )

     go

    /* END_SYBASE */

	/* BEGIN_SYBASE */

  CREATE TABLE AweSchTskPar
   (	Ide INT not NULL,
	IdeTsk INT,
	Nam VARCHAR(40) not NULL,
	Val VARCHAR(400),
	Src INT not NULL,
	Typ VARCHAR(100) not NULL
   )

     go

    /* END_SYBASE */

		/* BEGIN_SYBASE */

  CREATE TABLE HISAweSchCal
   (	HISOpe VARCHAR(20) not NULL,
	HISDat DATETIME not NULL,
	HISAct VARCHAR(1) not NULL,
	Ide INT,
	Nom VARCHAR(40),
	Des VARCHAR(250),
	Act INT
   )

     go

    /* END_SYBASE */

	/* BEGIN_SYBASE */

  CREATE TABLE HISAweSchCalDat
   (	HISOpe VARCHAR(20) not NULL,
	HISDat DATETIME not NULL,
	HISAct VARCHAR(1) not NULL,
	Ide INT,
	IdeCal INT,
	Nom VARCHAR(40),
	Dat DATETIME
   )

     go

    /* END_SYBASE */

	/* BEGIN_SYBASE */

  CREATE TABLE HISAweSchSrv
   (	HISOpe VARCHAR(20) not NULL,
	HISDat DATETIME not NULL,
	HISAct VARCHAR(1) not NULL,
	Ide INT,
	Nom VARCHAR(40),
	Pro VARCHAR(10),
	Hst VARCHAR(40),
	Prt VARCHAR(10),
	Act INT
   )

     go

    /* END_SYBASE */

		/* BEGIN_SYBASE */

  CREATE TABLE HISAweSchTsk
   (	HISOpe VARCHAR(20) not NULL,
	HISDat DATETIME not NULL,
	HISAct VARCHAR(1) not NULL,
	Ide INT,
	IdePAR INT,
	Nam VARCHAR(40),
	Des VARCHAR(250),
	NumStoExe INT,
	TimOutExe INT,
	TypExe INT,
	IdeSrvExe INT,
	CmdExe VARCHAR(250),
	TypLch INT,
	LchDepErr INT,
	LchDepWrn INT,
	LchSetWrn INT,
	BLKPAR INT,
	RepTyp INT,
	RepEmaSrv INT,
	RepSndSta VARCHAR(20),
	RepEmaDst VARCHAR(250),
	RepTit VARCHAR(100),
	RepMsg VARCHAR(250),
	Act INT,
	RepUsrDst VARCHAR(250),
  RepMntId VARCHAR(200),
  CmdExePth VARCHAR(200)
   )

     go

    /* END_SYBASE */

	/* BEGIN_SYBASE */

  CREATE TABLE HISAweSchTskLch
   (	HISOpe VARCHAR(20) not NULL,
	HISDat DATETIME not NULL,
	HISAct VARCHAR(1) not NULL,
	Ide INT,
	IdeTsk INT,
	RptNum INT,
	RptTyp INT,
	IniDat DATETIME,
	EndDat DATETIME,
	IniTim VARCHAR(8),
	EndTim VARCHAR(8),
	IdeCal INT,
	IdSrv INT,
	Pth VARCHAR(250),
	Pat VARCHAR(250),
	ExeMth VARCHAR(200),
	ExeDay VARCHAR(200),
	ExeHrs VARCHAR(200),
	ExeDte DATETIME,
	ExeTim VARCHAR(8),
	WeekDays VARCHAR(200),
	ExeYrs VARCHAR(200),
	ExeMin VARCHAR(200),
	ExeSec VARCHAR(200),
  SrvUsr VARCHAR(200),
  SrvPwd VARCHAR(200)
   )

     go

    /* END_SYBASE */

		/* BEGIN_SYBASE */

  CREATE TABLE HISAweSchTskPar
   (	HISOpe VARCHAR(20) not NULL,
	HISDat DATETIME not NULL,
	HISAct VARCHAR(1) not NULL,
	Ide INT,
	IdeTsk INT,
	Nam VARCHAR(40),
	Val VARCHAR(400),
	Src INT,
	Typ VARCHAR(100)
   )

     go

    /* END_SYBASE */

   /* BEGIN_SYBASE */

   ALTER TABLE AweSchCal ADD CONSTRAINT Nom_UQ  UNIQUE (Nom)

     go

    /* END_SYBASE */

   /* BEGIN_SYBASE */

  ALTER TABLE AweSchCal ADD CONSTRAINT PK_AweSchCal UNIQUE (Ide)

     go

    /* END_SYBASE */

   /* BEGIN_SYBASE */

  ALTER TABLE AweSchCalDat ADD CONSTRAINT PK_AweSchCalDat UNIQUE (Ide)

     go

    /* END_SYBASE */

   /* BEGIN_SYBASE */

  CREATE INDEX AweSchExeI1 ON AweSchExe (IdeTsk, IniDat)

     go

    /* END_SYBASE */

   /* BEGIN_SYBASE */

  ALTER TABLE AweSchSrv ADD CONSTRAINT PK_AweSchSrv UNIQUE (Ide)

     go

    /* END_SYBASE */

   /* BEGIN_SYBASE */

  ALTER TABLE AweSchTsk ADD CONSTRAINT PK_AweSchTsk UNIQUE (Ide)

     go

    /* END_SYBASE */

   /* BEGIN_SYBASE */

  ALTER TABLE AweSchTskAvgTim ADD CONSTRAINT SYS_C00167154 UNIQUE (Ide)

     go

    /* END_SYBASE */

   /* BEGIN_SYBASE */

  ALTER TABLE AweSchTskDpn ADD CONSTRAINT SYS_C00164575 UNIQUE (IdeTsk, IdePrn)

     go

    /* END_SYBASE */

   /* BEGIN_SYBASE */

  ALTER TABLE AweSchTskLch ADD CONSTRAINT PK_AweSchTskLch UNIQUE (Ide)

     go

    /* END_SYBASE */

   /* BEGIN_SYBASE */

  ALTER TABLE AweSchTskPar ADD CONSTRAINT PK_AweSchTskPar UNIQUE (Ide)

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  CREATE INDEX HISAweSchCalI1 ON HISAweSchCal (HISOpe, HISDat, HISAct)

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  CREATE INDEX HISAweSchCalDatI1 ON HISAweSchCalDat (HISOpe, HISDat, HISAct)

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  CREATE INDEX HISAweSchSrvI1 ON HISAweSchSrv (HISOpe, HISDat, HISAct)

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  CREATE INDEX HISAweSchTskI1 ON HISAweSchTsk (HISOpe, HISDat, HISAct)

     go

    /* END_SYBASE */

  /* BEGIN_SYBASE */

  CREATE INDEX HISAweSchTskLchI1 ON HISAweSchTskLch (HISOpe, HISDat, HISAct)

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  CREATE INDEX HISAweSchTskParI1 ON HISAweSchTskPar (HISOpe, HISDat, HISAct)

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  ALTER TABLE AweSchCal ADD CONSTRAINT PK_AweSchCal PRIMARY KEY (Ide)

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  ALTER TABLE AweSchTskFilMod ADD CONSTRAINT PK_AweSchTskFilMod PRIMARY KEY (IdeTsk , FilPth)

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  ALTER TABLE AweSchCalDat ADD CONSTRAINT PK_AweSchCalDat PRIMARY KEY (Ide)

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */
  ALTER TABLE AweSchSrv ADD CONSTRAINT PK_AweSchSrv PRIMARY KEY (Ide)

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  ALTER TABLE AweSchTsk ADD CONSTRAINT PK_AweSchTsk PRIMARY KEY (Ide)

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  ALTER TABLE AweSchTskAvgTim ADD PRIMARY KEY (Ide)

     go

    /* END_SYBASE */

/* BEGIN_SYBASE */

  ALTER TABLE AweSchTskDpn ADD PRIMARY KEY (IdeTsk, IdePrn)

     go

    /* END_SYBASE */

 /* BEGIN_SYBASE */

  ALTER TABLE AweSchTskLch ADD CONSTRAINT PK_AweSchTskLch PRIMARY KEY (Ide)

     go

    /* END_SYBASE */

 /* BEGIN_SYBASE */

  ALTER TABLE AweSchTskPar ADD CONSTRAINT PK_AweSchTskPar PRIMARY KEY (Ide)


     go

    /* END_SYBASE */


Insert into AweKey (KeyNam, KeyVal) Values ('SchTskAvgTimKey', 0)
go
Insert into AweKey (KeyNam, KeyVal) Values ('SchTskKey', 0)
go
Insert into AweKey (KeyNam, KeyVal) Values ('SchTskExe', 0)
go
Insert into AweKey (KeyNam, KeyVal) Values ('SchTskCal', 0)
go
Insert into AweKey (KeyNam, KeyVal) Values ('SchTskCalDat', 0)
go
Insert into AweKey (KeyNam, KeyVal) Values ('SchTskSrv', 0)
go
Insert into AweKey (KeyNam, KeyVal) Values ('SchTskLch', 0)
go
Insert into AweKey (KeyNam, KeyVal) Values ('SchTskPar', 0)
go
