apiVersion: apps/v1
kind: Deployment
metadata:
  name: awe-boot-$CI_ENVIRONMENT_SLUG
  annotations:
    app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
    app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
  labels:
    app: $CI_PROJECT_PATH_SLUG
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $CI_PROJECT_PATH_SLUG
  template:
    metadata:
      annotations:
        app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
        app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
      labels:
        app: $CI_PROJECT_PATH_SLUG
    spec:
      containers:
      - name: awe-boot
        image: registry.gitlab.com/aweframework/awe/awe-boot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
      imagePullSecrets:
        - name: registry.gitlab.com