--------------------------------------------------------
--  NOTIFIER DDL
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table AweSub
--  Subscriptions
--------------------------------------------------------
CREATE TABLE "AWESUB"
(
    "IDE" NUMBER(*, 0),
    "ACR" VARCHAR2(10 BYTE),
    "NOM" VARCHAR2(30 BYTE),
    "DES" VARCHAR2(250 BYTE),
    "ACT" NUMBER(*, 0) DEFAULT 1
);

CREATE UNIQUE INDEX "PK_AWESUB" ON AWESUB ("IDE");
ALTER TABLE "AWESUB" ADD CONSTRAINT PK_AWESUB PRIMARY KEY ("IDE");
ALTER TABLE "AWESUB" MODIFY ("IDE" NOT NULL ENABLE);
ALTER TABLE "AWESUB" MODIFY ("ACR" NOT NULL ENABLE);
ALTER TABLE "AWESUB" MODIFY ("NOM" NOT NULL ENABLE);
ALTER TABLE "AWESUB" MODIFY ("ACT" NOT NULL ENABLE);

-- HISTORIC TABLE
CREATE TABLE "HISAWESUB"
(
    "HISOPE" VARCHAR2(20 BYTE),
    "HISDAT" DATE,
    "HISACT" VARCHAR2(1 BYTE),
    "IDE"    NUMBER(*, 0),
    "ACR"    VARCHAR2(10 BYTE),
    "NOM"    VARCHAR2(30 BYTE),
    "DES"    VARCHAR2(250 BYTE),
    "ACT"    NUMBER(*, 0)
);

ALTER TABLE "HISAWESUB" MODIFY ("HISOPE" NOT NULL ENABLE);
ALTER TABLE "HISAWESUB" MODIFY ("HISDAT" NOT NULL ENABLE);
ALTER TABLE "HISAWESUB" MODIFY ("HISACT" NOT NULL ENABLE);
CREATE INDEX "HISAWESUBI1" ON HISAWESUB (HISOPE, HISDAT, HISACT);

--------------------------------------------------------
--  DDL for Table AweSubUsr
--  User subscriptions
--------------------------------------------------------
CREATE TABLE "AWESUBUSR"
(
    "IDE"    NUMBER(*, 0),
    "IDEOPE" NUMBER(*, 0),
    "IDESUB" NUMBER(*, 0),
    "SUBNOT" NUMBER(*, 0) DEFAULT 1,
    "SUBEMA" NUMBER(*, 0) DEFAULT 0
);

CREATE UNIQUE INDEX "PK_AWESUBUSR" ON AWESUBUSR ("IDE");
ALTER TABLE "AWESUBUSR" ADD CONSTRAINT PK_AWESUBUSR PRIMARY KEY ("IDE");
ALTER TABLE "AWESUBUSR" MODIFY ("IDE" NOT NULL ENABLE);
ALTER TABLE "AWESUBUSR" MODIFY ("IDEOPE" NOT NULL ENABLE);
ALTER TABLE "AWESUBUSR" MODIFY ("IDESUB" NOT NULL ENABLE);
ALTER TABLE "AWESUBUSR" MODIFY ("SUBNOT" NOT NULL ENABLE);
ALTER TABLE "AWESUBUSR" MODIFY ("SUBEMA" NOT NULL ENABLE);

-- HISTORIC TABLE
CREATE TABLE "HISAWESUBUSR"
(
    "HISOPE" VARCHAR2(20 BYTE),
    "HISDAT" DATE,
    "HISACT" VARCHAR2(1 BYTE),
    "IDE"    NUMBER(*, 0),
    "IDEOPE" NUMBER(*, 0),
    "IDESUB" NUMBER(*, 0),
    "SUBNOT" NUMBER(*, 0),
    "SUBEMA" NUMBER(*, 0)
);

ALTER TABLE "HISAWESUBUSR" MODIFY ("HISOPE" NOT NULL ENABLE);
ALTER TABLE "HISAWESUBUSR" MODIFY ("HISDAT" NOT NULL ENABLE);
ALTER TABLE "HISAWESUBUSR" MODIFY ("HISACT" NOT NULL ENABLE);
CREATE INDEX "HISAWESUBUSRI1" ON HISAWESUBUSR (HISOPE, HISDAT, HISACT);

--------------------------------------------------------
--  DDL for Table AweNot
--  Notifications
--------------------------------------------------------
CREATE TABLE "AWENOT"
(
    "IDE"    NUMBER(*, 0),
    "IDESUB" NUMBER(*, 0),
    "TYP"    VARCHAR2(10 BYTE),
    "ICO"    VARCHAR2(30 BYTE),
    "NOM"    VARCHAR2(30 BYTE),
    "DES"    VARCHAR2(250 BYTE),
    "SCR"    VARCHAR2(100 BYTE),
    "COD"    VARCHAR2(100 BYTE),
    "DAT"    TIMESTAMP
);

CREATE UNIQUE INDEX "PK_AWENOT" ON AWENOT ("IDE");
ALTER TABLE "AWENOT" ADD CONSTRAINT PK_AWENOT PRIMARY KEY ("IDE");
ALTER TABLE "AWENOT" MODIFY ("IDE" NOT NULL ENABLE);
ALTER TABLE "AWENOT" MODIFY ("IDESUB" NOT NULL ENABLE);
ALTER TABLE "AWENOT" MODIFY ("TYP" NOT NULL ENABLE);
ALTER TABLE "AWENOT" MODIFY ("ICO" NOT NULL ENABLE);
ALTER TABLE "AWENOT" MODIFY ("NOM" NOT NULL ENABLE);
ALTER TABLE "AWENOT" MODIFY ("DAT" NOT NULL ENABLE);

-- HISTORIC TABLE
CREATE TABLE "HISAWENOT"
(
    "HISOPE" VARCHAR2(20 BYTE),
    "HISDAT" DATE,
    "HISACT" VARCHAR2(1 BYTE),
    "IDE"    NUMBER(*, 0),
    "IDESUB" NUMBER(*, 0),
    "TYP"    VARCHAR2(10 BYTE),
    "ICO"    VARCHAR2(30 BYTE),
    "NOM"    VARCHAR2(30 BYTE),
    "DES"    VARCHAR2(250 BYTE),
    "SCR"    VARCHAR2(100 BYTE),
    "COD"    VARCHAR2(100 BYTE),
    "DAT"    TIMESTAMP
);

ALTER TABLE "HISAWENOT" MODIFY ("HISOPE" NOT NULL ENABLE);
ALTER TABLE "HISAWENOT" MODIFY ("HISDAT" NOT NULL ENABLE);
ALTER TABLE "HISAWENOT" MODIFY ("HISACT" NOT NULL ENABLE);
CREATE INDEX "HISAWENOTI1" ON HISAWENOT (HISOPE, HISDAT, HISACT);

--------------------------------------------------------
--  DDL for Table AweNotUsr
--  User notifications
--------------------------------------------------------
CREATE TABLE "AWENOTUSR"
(
    "IDE"    NUMBER(*, 0),
    "IDEOPE" NUMBER(*, 0),
    "IDENOT" NUMBER(*, 0),
    "UNR"    NUMBER(*, 0) DEFAULT 1
);

CREATE UNIQUE INDEX "PK_AWENOTUSR" ON AWENOTUSR ("IDE");
ALTER TABLE "AWENOTUSR" ADD CONSTRAINT PK_AWENOTUSR PRIMARY KEY ("IDE");
ALTER TABLE "AWENOTUSR" MODIFY ("IDE" NOT NULL ENABLE);
ALTER TABLE "AWENOTUSR" MODIFY ("IDEOPE" NOT NULL ENABLE);
ALTER TABLE "AWENOTUSR" MODIFY ("IDENOT" NOT NULL ENABLE);
ALTER TABLE "AWENOTUSR" MODIFY ("UNR" NOT NULL ENABLE);

-- HISTORIC TABLE
CREATE TABLE "HISAWENOTUSR"
(
    "HISOPE"    VARCHAR2(20 BYTE),
    "HISDAT"    DATE,
    "HISACT"    VARCHAR2(1 BYTE),
    "IDE"       NUMBER(*, 0),
    "IDEOPE"    NUMBER(*, 0),
    "IDENOT"    NUMBER(*, 0),
    "UNR"       NUMBER(*, 0)
);

ALTER TABLE "HISAWENOTUSR" MODIFY ("HISOPE" NOT NULL ENABLE);
ALTER TABLE "HISAWENOTUSR" MODIFY ("HISDAT" NOT NULL ENABLE);
ALTER TABLE "HISAWENOTUSR" MODIFY ("HISACT" NOT NULL ENABLE);
CREATE INDEX "HISAWENOTUSRI1" ON HISAWENOTUSR (HISOPE, HISDAT, HISACT);

--------------------------------------------------------
--  SEQUENCES
--------------------------------------------------------
insert into AweKey (KeyNam, KeyVal) values ('Sub', (select coalesce(max(Ide),0) + 1 from AweSub));
insert into AweKey (KeyNam, KeyVal) values ('SubUsr', (select coalesce(max(Ide),0) + 1 from AweSubUsr));
insert into AweKey (KeyNam, KeyVal) values ('Not', (select coalesce(max(Ide),0) + 1 from AweNot));
insert into AweKey (KeyNam, KeyVal) values ('NotUsr', (select coalesce(max(Ide),0) + 1 from AweNotUsr));

